### ISSUE TITLE
Register and Sign up with GNU social and diaspora*

### ISSUE THREAD

**Issue by GreenLunar** [OpenUserJS/OpenUserJS.org#1032]
Apparently, it is not yet possible.

**Comment by Martii** [comment]
> Apparently, it is not yet possible.

Neither are present there under these names.

Ref(s):
* http://passportjs.org/

**Comment by GreenLunar** [comment]
I think both use OAuth, which is available.

GNU social was formerly known as StatusNet. See https://github.com/zoowar/passport-statusnet

**Comment by zuimanhua** [comment]
不太好说呀！

**Comment by Martii** [comment]
@GreenLunar 
It would seem that your issue was closed at zoowar/passport-statusnet#1

At least we know the author is alive after ~5 years. ;)

This is so far down on the TODO list and because the author closed it without responding I don't think that we're going to be adding this auth.

Appreciate the suggestion though. :)

**Comment by Martii** [comment]
@GreenLunar 
As per sizzle and myself with the observed lack of *passport-statusnet* support we won't be supporting this. Appreciate the suggestion though.
