### ISSUE TITLE
Problem after logging in

### ISSUE THREAD

**Issue by dexter777** [OpenUserJs/OpenUserJS.org#1052]
On OpenUserJS I have an account "Dexter86" which authenticates using
my Google account. Just now, when I tried to login, it logged me to
account "dexter86" (notice the difference, D & d). And I can't do
anything with my scripts, I can only fork them. It's like it treats me as different user.

**Comment by Martii** [comment]
I can rename `dexter86` but your auths are different... in other words... either you or google resent the authentication challenge and OUJS created a new account. If you can't get your google restore to the original account then `Dexter86` will be orphaned.

Possibly applies to #484

**Comment by Martii** [comment]
Renamed `dexter86` to `Dexter86_1`

**Comment by dexter777** [comment]
That's just great... Now when I login using Dexter86 it logs me to Dexter86_1. I just want to restore access to my Dexter86 account. I can't update my scripts :[ It worked without problems 3 month ago.

> either you or google resent the authentication challenge
I don't even know how to do that, that must be a problem on your end or google.

> If you can't get your google restored to the original account then Dexter86 will be orphaned
I don't even understand what do you mean by that, I use the same google account.

**Comment by Martii** [comment]
> I don't even understand what do you mean by that

Means exactly that it's no longer accessible... and you get to use the other account since Google provided you with a different authentication key. We have no control over that.

Issue is now closed since you don't want a different username for `Dexter86_1`. We have no way of proving that original account is yours and you didn't add a secondary authentication to work around issues that are known to exist with Google such as GitHub.
