### ISSUE TITLE
Can anyone help to remove my account with email address

### ISSUE THREAD

**Issue by iMingLei** [OpenUserJs/OpenUserJS.org#1142]
I just ignored the caution part. Please help.

**Comment by Martii** [comment]
Leave me a message in your profile on the account with my GH username here requesting removal and I'll look into it.

**Comment by iMingLei** [comment]
Profiles updated for two accounts. Thanks very much in advance.

**Comment by Martii** [comment]
Because you had activity with your first created account that has to stay... so what was your username you signed up with your twitter account is now your user name to login and all of your auths are merged into that first, oldest, account... but renamed free of email, scrubbed, portion. 

If you need to toggle which is primary please use https://openuserjs.org/user/preferences after you log out and then log in... or before you login use the register field with your current username *(not email)* and select the auth source type and click register manually and it will change to that default.

Ref:
#233

**Comment by iMingLei** [comment]
Thanks, Martii.
