### ISSUE TITLE
Chrome has like QupZilla native Userscript Support

### ISSUE THREAD

**Issue by alugarius** [OpenUserJs/OpenUserJS.org#1145]
You should get your stuff right

**Comment by Martii** [comment]
@alugarius 

> You should get your stuff right

Please tread lightly here... the TOS applies to development as well. So please be a little more polite.

Chromium/Chrome has always had **after** Fx a watered down version of .user.js however it's not enhanced and is usually not recommended due to its lack of features. The wording in the documentation is clear for anyone who reads well. If you wish to expand upon it you may open a PR to be evaluated.

Thank you.
