### ISSUE TITLE
Expired SSL certificate

### ISSUE THREAD

**Issue by iStyx** [OpenUserJS/OpenUserJS.org#1255]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/2x2E0F3j473o122Y331m/%5B3119f2b6f24a8c4e65e626e781f2489c%5D_Screen+Shot+2017-11-15+at+6.55.43+PM.png?X-CloudApp-Visitor-Id=1084640)

**Comment by Martii** [comment]
Thanks. Just noticed that on a site check. @sizzlemctwizzle has been messaged.

**Comment by Martii** [comment]
Going to do some maintenance compiling... so the site will be offline for about an hour.

**Comment by Martii** [comment]
Much quicker... so it's back online for those browsers that can add an exception until we hear back from @sizzlemctwizzle

**Comment by Alex-Tracer** [comment]
Any updates on this?
The site still inaccessible in the most of browsers (Firefox, Chrome).

**Comment by Martii** [comment]
> Any updates on this?

None. I haven't heard back.

> The site still inaccessible in the most of browsers (Firefox, Chrome).

You actually picked two of the browsers that **do** have access through an exception. SM is so far the only browser that hasn't been able to add the exception. But I realize this isn't much help as the webhook isn't allowed due to GH's security policy.

If I hear anything I'll post here. Looking into a short term third party certificates as a short term solution... but it would be better if @sizzlemctwizzle renewed his existing CA. I know where to put them on the server and I do have that ability but I'll have to prove that I am able to "own" the domain... this ought to be complicated I think.

**Comment by Alex-Tracer** [comment]
> two of the browsers that do have access through an exception

That's very strange because in my case browser explicitly refuses to add the exception.

Firefox message:
`This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.`

Chrome message:
`openuserjs.org normally uses encryption to protect your information. When Google Chrome tried to connect to openuserjs.org this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be openuserjs.org, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit openuserjs.org right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.`

**Comment by Martii** [comment]
What's your platform?... I haven't test on Mac yet but Windows and dev station Linux allow it. I have a few virtual machines too.

**Comment by Alex-Tracer** [comment]
Windows7 64bit.
Firefox 56.0.2
Chrome 62.0.3202.94

**Comment by Martii** [comment]
Well my Win7 x64 had 55, 56 and now 57... tested on all with the exception being there. There's a little "Advanced" button that shows up. Chrome on same platform was just tested and it also has an advanced link that brings up "Proceed to openuserjs.org (unsafe)" link. Are these en-US browser versions? *(check your useragent for some other language code)*

**Comment by Martii** [comment]
And SM for Win7 x64 2.48 then 2.49.1 has the exception add with "I understand the Risks" toggle... but not dev station Linux. I'll try a clean profile in a bit and non-admin.

**Comment by iStyx** [comment]
@Martii 
> Looking into a short term third party certificates as a short term solution...

You can try https://letsencrypt.org/, it really is easy to use.

**Comment by Martii** [comment]
Yah that's what I'm looking into... have to weigh the bot criteria on the server first and of course our users privacy. :)

**Comment by Martii** [comment]
certbot looks a lot like my local PHP configuration and we run *node*. :\ Like I said probably complicated. We won't be adding PHP to the VPS.

**Comment by iStyx** [comment]
@Martii you certainly don't need PHP in order to make it work, have a look at this: https://letsencrypt.readthedocs.io/en/latest/using.html#webroot

**Comment by Martii** [comment]
`/var/www/html` is a PHP path... that's not how *node* works. They also say that's where the server needs to be run... that's not the path.

I'm reading up on the greenlock packages to see if I can at least get one locally done for testing before I attempt on OUJS.

**Comment by Martii** [comment]
Tell you what ... I'll back up the VPS and try certbot but I seriously doubt that app is going to work. We'll be completely down for about 30 minutes. I'm not ready to install random binaries on the VPS without a fall back.

**Comment by Martii** [comment]
Documentation could use large improvements... looks like I got it hacked in. Definitely **not** and easy thing to do... and we seem to still have our A+ rating.

@sizzlemctwizzle When you get these communications these certs expire relatively quickly and it's not set up to auto-renew.

**Comment by LinogeFly** [comment]
I don't know if it's related to the certificate issue or not. But I can't upload new version of a script now on the website. It doesn't give me any error, but the script doesn't get updated when I press "Submit Code" button.

**Comment by Martii** [comment]
@LinogeFly 
Try Announcements... specifically [here](https://openuserjs.org/announcements/Licensing_enforcement).

**Comment by LinogeFly** [comment]
@Martii oh, I didn't know about Announcements section. Thanks! :)

**Comment by Martii** [comment]
K... we're back to the original renewed cert. Thanks to @sizzlemctwizzle 

Thanks everyone for your patience.
