### ISSUE TITLE
Can't sign in to openuserjs.org

### ISSUE THREAD

**Issue by vbagirov** [OpenUserJS/OpenUserJS.org#1320]
Hi, I am a member of [AdGuard](https://github.com/AdguardTeam) team, and I have a somewhat silly problem that I really can't find any way around.

Whenever I'm trying to sign in to OpenuserJS under the "corporate" account (adguard) I created specifically for the purpose of uploading AdGuard userscripts, I am seeing a `login?authfail` page, like this: https://uploads.adguard.com/vbagirovftw8a.png

When I click the "Sign In" button there (with GitHub selected as a preferred authentication method) I'm getting thrown back at the very same page. I'm able to sign in to my personal account on OpenuserJS without any issues at the same time.

Am I doing some stupid mistake somewhere or is there a possible bug?

**Comment by Martii** [comment]
> is there a possible bug?

I wouldn't be able to get in if there was a GH bug. Got in a few minutes ago. No system errors reported in logs.

> Am I doing some ... mistake somewhere

1. Account shows as GH for authentication... you didn't fidget with permissions here on GH to OUJS did you?
2. Try a clean browser profile... I ran into a weird issue a few weeks ago with my profile corrupting OAuth... didn't figure it out but a new clean profile and rebuilt fixed it.

> Am I doing some stupid mistake somewhere

1. Caps lock on? ;)
2. Correct password?

If all else fails the only way I can reset this is if the email used for `adguard` on GH creates another authentication... creates a new account on OUJS and puts a message directly here, and there, with that username saying fix me or the like... then I can merge it to the OUJS account then remove the GH auth and it can be redone with a new token.... otherwise orphaned.

**Comment by vbagirov** [comment]
@Martii sorry for long silence. I become more and more covinced that I messed something up upon signing up and used a GH account I don't usually use (I've went through all imaginable variants but to no success). 


I presume there's no way to restore the 'AdGuard' account on OUJS in this case? I'd be happy to be wrong.

**Comment by Martii** [comment]
> if I provide proof that I represent AdGuard?

Are you able to temporarily post a page *(not the forum)* over on https://adguard.com/en/ somewhere proving that @AdGuard is actually owned/managed by this domain?  Cc: @ameshkov *(mentioned as team lead)*

I do see you are currently one of the GH Owners over at https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/143#issue-283168375 so that helps solidify additional verification however I still need another auth on OUJS as I mentioned to merge and destroy the old auth token *(hash)*. 

The easiest solution is to message in this issue with @AdGuard and say it's okay ... then you can create another auth temporarily on OUJS *(use steam or something else other than GH)* and then I move that auth to https://openuserjs.org/users/AdGuard  and destroy the auth and token *(hash)* for GH allowing you to add GH back via https://openuserjs.org/user/preferences

> maybe it is possible to change the owner (author) of the Adguard Popup Blocker Beta script

Are you saying that the webhook on GH for @AdGuard is enabled and working? If so a GH commit match and OUJS Script source would assist... but again you still need an ancillary account after I get ultimate confirmation.

**Comment by vbagirov** [comment]
@Martii 

Turns out, I somehow signed up under the corporate account that I shouldn't have had access to. I was able to retrieve the credentials and all is fine now, the problem is solved. 

Thank you for your help and sorry for wasting your time. Closing the issue.

**Comment by ameshkov** [comment]
@Martii it's already late, but anyway, I can confirm that @adguard is our user :)
