### ISSUE TITLE
Adding a script with redirected @icon fails with error 500

### ISSUE THREAD

**Issue by monk-time** [OpenUserJS/OpenUserJS.org#1331]
I have published [a script](https://openuserjs.org/scripts/monk-time/IMDb_-_Clutter-less) that I can no longer update: apparently having `// @icon http://www.imdb.com/favicon.ico` prevents the site from accepting the script, although [the same icon](http://www.imdb.com/favicon.ico) worked fine for the previous update a few months ago. I get this error from OpenUserJS: 

> 500 
> `@icon` unsupported file type: undefined (file: undefined) 

I suspect this is caused by OpenUserJS not expecting the target site to redirect the icon, in this case from http://www.imdb.com/favicon.ico to https://ia.media-imdb.com/images/G/01/imdb/images/favicon-2165806970.

**Comment by Martii** [comment]
Same issue as with my gravatar at https://gravatar.com/avatar/7ff58eb098c23feafa72e0b4cd13f396&r=G&s=48&default=identicon ... however that doesn't do a redirect.

If you would please [create an issue with upstream](https://github.com/image-size/image-size/issues/new) I would appreciate it. I will tinker around with the `Buffer` to see if [their example](https://github.com/image-size/image-size/tree/bbf1e36505ba2d13cce175f64fba2492c84da9fd#using-a-url) is incorrect when I get some free time. This will be helpful to see what they have to say about it.

Ref(s):
* https://github.com/image-size/image-size/search?utf8=%E2%9C%93&q=ico+undefined&type= *(seeing if someone else reported this)*
* https://github.com/image-size/image-size *(dependency)*
* https://github.com/OpenUserJS/OpenUserJS.org/blob/be33f4ebd4109ce1857862ac421f103c2c315610/controllers/scriptStorage.js#L1488-L1496 *(Current rejection failure point at line 1489)*


In the short term if you might try a data uri or hosting the image elsewhere without the MIME Content-Type of `x-icon`. e.g. convert it to a png.

**Comment by Martii** [comment]
@monk-time 
Should work for you now... thanks for the report.

**Comment by Martii** [comment]
> First I got pain head because of license forcing.

Enforcement is the correct word... you agreed to it by continued use of the site in the TOS including not abusing any sites. It has been in there for years. End of this subject here as it's off topic and complain on your own time please.

> https://www.alienwarearena.com/favicon.ico

It would appear that the compression isn't supported on the .ico e.g. they use an unsupported frame and in a few browsers tested as well. Even has a warning in my .ico editor about it.

> Extremely frustrated.

Your choices for survival are:

1. Use a data URI of the size up to the maximum mentioned previously in another issue *(currently 256x256)*... I would suggest something more reasonable in size and fixed not a set of fixed images.
2. Host it somewhere else without that frame
3. Use a different, preferably more compatible, icon image
4. Open an issue with [that dependency](https://github.com/image-size/image-size/issues)... not us.

Our choices are migrating towards:
1. Remove .ico support *(which I'm still contemplating)* ... or 
2. *attempt to* limit it's file size **as well** *(with a reject on server hosting error with lack of size information sent)* because uncompressed that icon is ~1.5MiB *(compressed it is still ~359.1KiB which seems excessive at first glance... would need to compare some still images instead of a set of images)* which is again needlessly wasting everyone's bandwidth which is why the check is put in. e.g. as I put elsewhere one doesn't need to be a jerk to your users and especially the visitors. It's bad practice and bad showmanship which can lead to down voting and removal of a script if it gets too many/or any complaints.
3. If and when CORS is implemented that will also limit `@icon` usage depending on the target servers properties.

Refs:
* #1308 Read this as it is more applicable issue than this one... especially why everyone is even lucky it goes up to 256x256 currently.
