### ISSUE TITLE
Use cases for `@includes` and `@matches` in scripts.

### ISSUE THREAD

**Issue by Sxderp** [OpenUserJS/OpenUserJS.org#1333]
I posted a request on the usersScript API bugzilla about adjusting how `@include` and `@match` work (allow "OR") and they've asked for additional information regarding use cases. I suspect the majority of use cases, where both are used, have to do with the ability to use RegExp in `@include` but nevertheless, it would be great if some sort of details or statics could be provided on how scripts are currently using the fields. Any additional input is appreciated.

Bugzilla Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1437098#c2

@Martii 

Cross posted on greasyfork repo. https://github.com/JasonBarnabe/greasyfork/issues/536

Check out https://github.com/greasemonkey/greasemonkey/issues/2663 for various additional details.

**Comment by sizzlemctwizzle** [comment]
We could provide you with statistics or we could just give you the user script metadata for all user scripts on OUJS in JSON format. That might be of more use to you since you could preform any kind of analysis you want on the metadata yourself.

Anyway, it's up to @Martii on how he wants to provide the data.

**Comment by Sxderp** [comment]
Either would work. Though having all the meta data would be nice.

**Comment by Martii** [comment]
Collected meta for the UserScript metadata block and no libraries:

[collected_meta.json.zip](https://github.com/OpenUserJS/OpenUserJS.org/files/1754407/collected_meta.json.zip)

Actual metadata is larger because we don't collect everything but you'll have `@include` and `@match` values to twiddle with. Hitting the storage to regenerate for say `@history`, which has been seen on occasion, could get huge and tie up bandwidth. Data URI's are big enough and those are included for `@icon` and such. We currently collect at that block [here](https://github.com/OpenUserJS/OpenUserJS.org/blob/da49fff93a3fcd032f322adfc9031e5906d7fa3a/public/pegjs/blockUserScript.pegjs) with the same format as later GM3.x

As an Author myself I usually include the basic globs and then some depending on if a regular expression *(re)* is warranted... I even found trixie.msi in the archives the other day in which re's aren't supported and neither is `@match` since that was before scripting in Chrome/Chromium.

Typically I see Chrome/Chromium Authors use `@match` and GM Authors use `@include` but there there are exceptions.

---

Don't mind this... if my local storage medium croaks again and my backups fail like they did... it's here for reference:

``` js
// Dump collected (specific optional) metadata
var fs = require('fs');
var async = require('async');
var Script = require('./models/script').Script;
Script.find(
  {
    isLib: false
//     , 'meta.UserScript.include': { $exists: true }
//     , 'meta.UserScript.match': { $exists: true }

  }, function (aErr, aScripts) {
    var metas = [];

    if (aErr || !aScripts) {
      console.warn('no scripts found');
      return;
    }

    async.each(aScripts, function (aScript, aEachCallback) {
      metas.push(aScript.meta);

      process.nextTick(function() { aEachCallback(); }); // breathe
    }, function (aErr) {

      fs.writeFile('/home/user/collected_meta.json', JSON.stringify(metas, null, ' '), function (aErr) {
        if (aErr) {
          console.warn('error writing');
          return;
        }
        console.log('written');
      });
    });

  });
```

**Comment by Sxderp** [comment]
Hey thanks a lot. The archive has provided some interesting insights.

**Comment by Martii** [comment]
You are welcome and welcome anytime.
