### ISSUE TITLE
Yet another old user coming back after the Google fiasco

### ISSUE THREAD

**Issue by cbehan** [OpenUserJS/OpenUserJS.org#1356]
I read https://openuserjs.org/announcements/Google_Authentication_Deprecation and it seems like this is the reason that I'm seeing an authentication failure when trying to login. I don't remember mentioning links to my other accounts in my OpenUserJS.org account. However, I am hoping that the extreme similarity to my GreasyFork.org account is convincing enough.

https://openuserjs.org/users/ConnorBehan/scripts
5 scripts with 2 last updated in November 2015 and 3 last updated in January 2016.

https://greasyfork.org/en/users/183-connor-behan
5 scripts that are exactly the same with 1 last updated in November 2015 and 4 last updated in January 2016 since I try to keep them synchronized.

So my questions are the following.
1. Is there any other trace on the ConnorBehan account that I forgot about?
2. If not, will I be able to get my account back by posting something on greasy fork?
3. If not, could I send you the userscript I just wrote in order to have it posted under the ConnorBehan account?
If the answer to all three is "no" I completely understand. :)

**Comment by Martii** [comment]
1. Don't know about "forgot about" but there is one hope that I can think of... change your gravatar for the account that is mentioned at [USO mirror](http://userscripts-mirror.org/scripts/show/113484). Their site is still linked to gravatar so if you can change it, **TEMPORARILY** and preferably something that has OUJS or my GH username in it, and get back to me that should be the bit I need to weigh in on it. After I respond I would suggest changing it back e.g. backup your image first exactly as it saved in the browser for hash checking. e.g. don't use the one from here on GH unless you are 110% sure it's identical down to the bits *(hashes the same so maybe you can use it)*. They are the same number, albeit abstracted by GH, so that's a plus in your favor... but still need this full part for cross verification.

![gravatar](http://www.gravatar.com/avatar/e9a4dbda1c6805c05bc09c8326703d32?r=PG&s=92&default=identicon "SHA-256: 3d71a8725bac2ceba29ba87aadf13986f9caadd9092dc301237fa6e7ce8ea52c  13301871.jpeg")

2. Nope although I'm doing a hash check so do nothing on GF until I get done as it could invalidate me teetering towards doing this.
3. Definitely not.

**Comment by cbehan** [comment]
I have added a bio line near the top of <a href="https://greasyfork.org/en/users/183-connor-behan">GF</a> mentioning this issue. I also created the account <a href="https://openuserjs.org/users/cbehan">cbehan</a> on OUJS and set it to authenticate with GH.

Now about the pumpkin picture, Gravatar seems to perform its own tweaks to the images. When I view it on the official site, there is a "?size=" option in the URL that can be set arbitrarily. For 92, I get a different hash than the one in your post above. For 200, I get a different hash than the original 200x200 JPEG on my hard drive that I uploaded years ago. However, uploading a new image to Gravatar doesn't delete the old one. Despite the fact that I don't understand what they did, I can switch to a temporary image and then switch back without re-uploading.

**Comment by Martii** [comment]
@cbehan 
You're merged. Enter your old username into the appropriate text box and then change the authentication dropdown to GH. It will change to that default auth automatically in the future.

Just a note... when you don't log out, currently, I have to **boot everyone off while doing this maintenance** so your newly created *(and newly removed from the merge)* doesn't potentially crash the system. So as I'm sure someone else may come along and read this... always remember to Logout. I'm slowly working on a boot a single user option but finding time these days is a challenge and the session abstraction is massive.

As far as the Gravatar goes... don't bother with that. There's enough of a "+" tip there that I didn't really need it. Good to know what they have been up to though.

As far as the goo auth goes... what I said above... let me know.

**Comment by cbehan** [comment]
Thanks a lot! I agree with what you said... can you get rid of the old link to my Google account? Once it's gone, I will add a secondary authentication which will probably be Google again.

**Comment by Martii** [comment]
Goo is deleted... booted everyone off again ;) ... so you'll need to log back in using default GH then go to https://openuserjs.org/user/preferences to add your other auth... can switch default there too after authentication token is sent from goo.

**Comment by cbehan** [comment]
Done. And I was about to come back to the desk now and log out. I didn't know you would read this so quickly!

**Comment by Martii** [comment]
Glad it's working for you. Closing.
