### ISSUE TITLE
WebHooks aren't being processed?

### ISSUE THREAD

**Issue by joeytwiddle** [OpenUserJS/OpenUserJS.org#1730]
I often push updates to my userscripts, but it seems **some of** the new versions haven't been loaded from github for some time, whilst others have: https://openuserjs.org/users/joeytwiddle/scripts

For example, this one has changed a few times (see its History): https://github.com/joeytwiddle/code/blob/master/other/gm_scripts/Related_Links_Pager/Related_Links_Pager.user.js

**Do you have some debugging information about which part of the hooks process has a problem?**

The script mentioned above is 50KB, well within the 1MB limit specific in `settings.json` (at least in the dev settings).

I see the hooks process starts at `exports.webhook` in `scriptStorage.js` and goes on to call `repoManager.prototype.loadScripts` in `repoManager.js`.

I would assume the `fetchRaw()` is working as it is, but if you want me to add authentication to that, I could do that.

----

I just did a push to GitHub at `new Date(1596957303135)` so perhaps you might see something logged around that time.
https://openuserjs.org/scripts/joeytwiddle/Wikipedia_Inline_Article_Viewer
https://github.com/joeytwiddle/code/blob/master/other/gm_scripts/wikipedia_inline_article/wikipedia_inline_article.user.js

**Comment by Martii** [comment]
@joeytwiddle 

> Do you have some debugging information about which part of the hooks process has a problem?

We do not. We return the http status codes that shows up in your webhook logs on GH only. Browsing through the `console` messages in our source for errs I see nothing related to your account on OUJS. May have an issue with *mongoose*/*mongodb* dep though... updating those shortly.

> I would assume the fetchRaw() is working as it is, but if you want me to add authentication to that, I could do that.

Well as you know it probably isn't. I'll look at the PR in a bit but I'll probably have to try that VPS side directly since dev environment doesn't even process the webhook. If @sizzlemctwizzle would be available to review #1705 that would be appreciated.

> **some of** the new versions haven't been loaded from github for some time

I see a date updated difference on one of those. Although I just did my usual "Hello, World" test push and it sync'd well. You could be running into GH throttling with #1705 but unsure atm.

**Comment by joeytwiddle** [comment]
Recently on my Syncs page I am getting a lot of "Updating but no script found."

I think some years ago GM for Firefox might have lowercased all my script names, and I went along with it.

I can rename the file, but this is a bit of a hassle (and breaks some of my own processes).

Would it be possible to make the `findDeadorAlive()` query case-insensitive?

(And maybe fall back to a case-sensitive search, if multiple case-insensitive matches were found.)

**Comment by Martii** [comment]
> Would it be possible to make the `findDeadorAlive()` query case-insensitive?

Nope. I'm the one that was instructed to make it case sensitive and it should always be. See https://github.com/OpenUserJS/OpenUserJS.org/issues/656#issuecomment-118158810

Picking on one of your sync's at https://raw.githubusercontent.com/joeytwiddle/code/master/other/gm_scripts/wikimedia/wikimedia.user.js#bypass=true ... that isn't on OUJS with the `@name` of `Wikimedia Page History in Sidebar [adopted]` *(unsanitized for GM naming atm)*. And the only "Wikimedia" in a search you have is [here](https://openuserjs.org/scripts/joeytwiddle/Wikimedia+_for_Chrome_(localStorage)). This doesn't remotely resemble the GH `@name`.

* https://raw.githubusercontent.com/joeytwiddle/code/master/other/gm_scripts/imdb_large_images/iMDB_Large_Images.user.js#bypass=true currently shows for me 404 not found on GH ... that's could be an issue with GH.

etc.... Really don't want to go through all 40 of your scripts along with syncs to validate by hand... how about you do that and post back and I'll check those. :)


As you may have noticed we still get the update request notice if you don't publish a script to OUJS from GH's webhook... so keep that in mind. Those particular 404's you can ignore if you have **not** published to OUJS. However the GH issue one could be them... could be you... as long as the `@name`'s match between GH and OUJS it should retain your stats. If you change it then you lose the stats and it normally spawns off a new script because casing is important in the engines.

**Comment by joeytwiddle** [comment]
OK so it looks like the problem is that I recently added [fork] and [adopted] to the names of some of the scripts, to clearly distinguish which are original work and which are not. (When doing this, I did not change the filenames, just the `@name`.)

So, is there any way to smoothly rename a script on OUJS?

**Comment by Martii** [comment]
> had [no problem](https://greasyfork.org/en/users/8615-joeytwiddle) with my renames.

That's because you are just a number over there ... https://greasyfork.org/en/users/8615-you_are_just_a_number_over_there

> even if it is desirable.

It's not and sizzle won't agree with it either from past historical posts.

> I should consider whether to un-rename all my scripts back to how they were before

Your choice... but you could have modified `@description` to indicate a "fork" although usually license tags and headers do that for you from the upstream source.
