### ISSUE TITLE
TLS expired and site inaccessible

### ISSUE THREAD

**Issue by maximilianotaverna** [OpenUserJS/OpenUserJS.org#1776]
checked with a few online services and appears the site is down..

**Comment by dezgasting** [comment]
same question. site has been down for two days at this point

**Comment by Martii** [comment]
Certs expired yesterday morning about 24 hours'ish ago. Still awaiting new ones from @sizzlemctwizzle 

If your browsers allow it use http until I get back to dev station.

**Comment by Martii** [comment]
Working on temporary certs... perhaps more permanent if I can resolve some issues with the certification application.

**Comment by Martii** [comment]
Well letsencrypt is a bust... tried 5 times and hit their rate limit *(which isn't what they claim [their limits](https://letsencrypt.org/docs/rate-limits/) are)*. Useless service IMHO. Have to wait for @sizzlemctwizzle to generate the normal ones hopefully.

**Comment by Martii** [comment]
Got some temporary ones up. Whether or not these are permanent is all dependent upon certbot maintaining what permissions I put in. i.e. when renewal is triggered if the perms change *(or the keys)* that may take the server out of TLS again. Cc: @sizzlemctwizzle 

Plus our VPS was putting in some extra garbage into the record... so that's why it failed on try 5... preferring DNS validation as that is independent of everything. And of course only getting a few tests on initial.

Next expiration date claims to be February 14, 2021 according to the cert.

**Comment by Martii** [comment]
Update:

Oh Goody! *(sarcasm)*

A *node* and/or *request* glitch via openssl with `ERR_TLS_CERT_ALTNAME_INVALID` when testing current LetsEncrypt certificates on dev. :\ Throws/captures the error *(`aErr`)*, lets me print it *(`aErr.code`)*, but doesn't let me trap it so far in current dev configuration *(`else` case for any other error)*. 

Will work on this after some snoozing.

**Comment by Martii** [comment]
This should be good to go... will replace LE with GD certs in a while.
