### ISSUE TITLE
DMCA sign question

### ISSUE THREAD

**Issue by BogudanPro** [OpenUserJS/OpenUserJS.org#1814]
On your page about DMCA there is this point:
`7. Digitally sign the email.`

My question is: can I use self-signed certificate for it?

**Comment by Martii** [comment]
I think you are taking this a little too techie... digital signature usually means a legal form of identification. Your actual name is required by law. Think of any website that makes you enter your name as a legal signature... or PDF for example.

If you have an issue you may also flag a script for inspection... just be concise on why and validate a claim. If a source is behind a paywall or other similar mechanism then it makes it near impossible to validate.

**Comment by BogudanPro** [comment]
I may be really going too technical, but it's first time I met digital signature requirement. Including "any website that makes you enter your name as a legal signature... or PDF signature" -- i've never met these.

Do I need to login on site to flag scripts?

**Comment by Martii** [comment]
>  i've never met these.

I have a lot of times for just about every contract online... pick a cell phone sign up for example. There are a lot of places where you type in your real name/contact information. If a DMCA comes in without a legal, confirmed, contact then it may be dismissed.

> Do I need to login on site to flag scripts?

Yes.

**Comment by BogudanPro** [comment]
What is "cell phone sign up"?

**Comment by Martii** [comment]
Something that's beyond the scope of this repo... plus you can search for things like that question. You have your answer for the topic.

**Comment by BogudanPro** [comment]
Well I tried to search for it, but found nothing :(

**Comment by Martii** [comment]
@BogudanPro 

See... a simple flagging and possibly drawing attention to your issue works provided there is ample evidence... which you provided.

**Comment by Martii** [comment]
@BogudanPro 

Btw for your other flag you will need to be more explicit with what line numbers you are talking about. You may right click the offending script line numbers for a link to the start of what you are wanting to be investgated, then unflag the script, then reflag it with the new comment which should include any line numbers. A simple between line and line link reference will assist in determining your validation please.

**Comment by Martii** [comment]
@BogudanPro 

FYI this is the diff map for your requested flag:

![diff map](https://user-images.githubusercontent.com/114709/120546859-96b2f080-c3ad-11eb-919b-b4dd1318e1d6.png)

A lot of green means it's very much a derivative.

In the future on your source repo **do not delete older versions** as it will skew this process. Since 2.6.4 isn't there on your repo the results need to be manually checked which can be more lead time to investigate. Also 2.6.0, which is what was compared against the target, was ND so definitely shouldn't have been put up on OUJS. Pick a license and stick with it in the future. I do see the similarities so it is granted as valid.

What that particular author should have done is `@require`d your script then it would avoid issues like these thus giving you the accountability.

P.S. I've briefly unlocked the conversation but it will be relocked here shortly.

**Comment by BogudanPro** [comment]
O meant 2.6.4 of Plain old youtube (2020) | 7KT EDITION. Source script version to compare is around 2.3.0.
Also, GreasyFork does not have "delete version" thing AFAIK.

**Comment by Martii** [comment]
As I mentioned on OUJS, before your target flag script was removed and new offender was removed for blatantly reposting your script a little bit ago... stick to flagging and it will get investigated. It is best to keep things as publicly anonymous as possible in public comments too so you don't get retaliation. i.e. on OUJS just private flag on GH keep things like "target" instead of specific script names.

You may always read my comments, if I make them, at https://openuserjs.org/users/Marti/comments ... and I'm also moderating at Martii as described in my profile... but actions are taken via OUJS Admin duties... and here on GH I'm a co-owner.
