### ISSUE TITLE
Clear "issues answer" in removed scripts

### ISSUE THREAD

**Issue by raingart** [OpenUserJS/OpenUserJS.org#1833]
After deleting the script, a comment remains. There is no way to remove or hide it.
Requirements: the ability to delete your own (maybe someone else's) comments in your project.
Requirement 2: when deleting a project, delete all resources related to it (comments, issues, etc.)

Aliexpress USD <-- removed!
![Screenshot from 2021-08-16 21-16-59](https://user-images.githubusercontent.com/13064767/129611020-6ecf6662-398f-4447-8d3c-83852f3230eb.png)

**Comment by Martii** [comment]
@raingart 

> After deleting the script, a comment remains

This is by design to prevent bad actors actors from circumventing evaluation by doing exactly what you mentioned by deleting their script to cover things up.

> the ability to delete your own (maybe someone else's) comments in your project.

At some point way down the line there will be a vote up/down *(or similar)* to the discussion and comments but for now it is as it is.

> when deleting a project, delete all resources related to it (comments, issues, etc.)

Already discussed at the beginning of this comment.
