### ISSUE TITLE
429 Too many requests.

### ISSUE THREAD

**Issue by raingart** [OpenUserJS/OpenUserJS.org#1928]
```
429 Too many requests.
Please retry after approximately 86460 seconds.
```

I have been unable to enter the site for 3 days to update the script.
Perhaps the problem is that the first day I tried two different operating systems.

And I also believe that few people know that 86460 seconds is 24 hours. And why not bring time into a human-readable system of calculations.

**Comment by Martii** [comment]
> I have been unable to enter the site for 3 days to update the script.

Your last authed date is 2022-01-06T14:57:50.223Z and I watched you get in and the times you didn't. i.e. you didn't listen to what the system was telling you and that's two days not three.

>  the first day I tried two different operating systems.

As you mentioned afterwards with:

> 86460 seconds is 24 hours

... you tried twice, by your own admission, which resets the time again by design.

> And why not bring time into a human-readable system of calculations.

Been thinking about that but the bad actors aren't the brightest bulbs out there and it's good to keep them busy figuring it out for improvements sake. Will think about it though.

Just as a FYI you have less than one more month on the previously mentioned interim temporary probation period where you won't have to worry about it. When scoring gets calculated a lot of your inconveniences may vanish depending on how the calculations come out.

Thanks for the report.

**Comment by Martii** [comment]
Btw here is a quick summary of how often we're seeing bad actors for those who are watching. Just in the last 14 hours approximately...

```
324640 81.81% 112397 85.00% 881.32 MiB 2xx Success
39189  9.88%  24759 18.72%  47.52 KiB 3xx Redirection
33001  8.32%      0  0.00%   2.76 KiB 4xx Client Errors
```

... note the 33,001 times. Most are 429's. So it is absolutely staying.

**Comment by Martii** [comment]
and just in the time it took me to post that comment it's up to 33452.
