### ISSUE TITLE
Github webhooks get 400 response 

### ISSUE THREAD

**Issue by techmovie** [OpenUserJS/OpenUserJS.org#1946]
**What happened?**

repository:https://github.com/techmovie/easy-upload
default branch: master
content-type: application/x-www-form-urlencoded

<img width="492" alt="image" src="https://user-images.githubusercontent.com/59314774/153847822-ae1f862b-3403-4c12-8e8c-23800b4d82da.png">

**What did you expect to happen?**

  Sync my github releases successfully.

**What the problem might be**

**Comment by Martii** [comment]
Works for me:

Refs:
* https://openuserjs.org/scripts/Marti/RFC_2606%C2%A73_-_Hello,_World!
* https://github.com/Martii/UserScripts/commit/4b28d23e48756ae4f82dcc24ee1e1f111e8970a7

I see no syncs on your OUJS account and also https://openuserjs.org/scripts/birdplane/EasyUpload_PT%E4%B8%80%E9%94%AE%E8%BD%AC%E7%A7%8D and https://github.com/techmovie/easy-upload/blob/master/dist/easy-upload.user.js have different dates... the latter being older... so it's possible you manually did an update on OUJS which shouldn't make a difference but it does point to your build routine on GH failing to create the newer version of your script. The delay in processing would never be that great *(one day or so)*... so possible GH hiccup as well depending on what you omitted in your report.

Just a FYI... if you see a 4xx code that's not us... it would be you perhaps via a GH hiccup.

And I also noticed in this:

<img src="https://user-images.githubusercontent.com/59314774/153847822-ae1f862b-3403-4c12-8e8c-23800b4d82da.png" width="492">

That the event you are showing is an `issues` for `X-GitHub-Event` which we do not support. So that screen shot is not helpful atm. It should be `push`... again user error.
