### ISSUE TITLE
Include rating in meta JSON

### ISSUE THREAD

**Issue by DenverCoder1** [OpenUserJS/OpenUserJS.org#1961]
Rating is missing from meta JSON

Example: https://openuserjs.org/meta/NatoBoram/YouTube_Comment_Blacklist.meta.json

`installs` and `issues` appear but `rating` does not.

This would be useful for https://github.com/badges/shields/issues/5505.

**Comment by DenverCoder1** [comment]
From the fact that shields.io support [many rating badges](https://shields.io/category/rating), it seems like being able to display the rating of a script in a readme is popular among users. Therefore it would be convenient to have an API to retrieve that value.

As it's a statistic that appears on the site, it would make sense if it were in the API, although you can feel free to disagree.

**Comment by DenverCoder1** [comment]
I see what you mean. I'm not too familiar with how the rating system works and wasn't sure if it was a simple count of votes or something more complex.

If the number of votes is something that's easily accessible, maybe that would be more meaningful as a badge statistic?

**Comment by Martii** [comment]
Both are currently static values but both are calculated on-the-fly *(to an aggregation using your terms elsewhere)*... so can be positive or negative. Other factors also affect both calculated values such as flagging and moderation.

**Comment by Martii** [comment]
calebcartwright [wrote](https://github.com/badges/shields/pull/8080#discussion_r897278144):
> I think it would be best to at least pull out the rating badges from this PR so we can go ahead and get the rest of them merged, and then circle back to if/when/how on the ratings badges

We can add ratings in but it would be nice to know if there the negative/positive equivalent/inverse of `nonNegativeInteger`. As I don't use *joi* in the documentation it doesn't come up with a quick document search in [their current API](https://joi.dev/api/).

I should also give fair warning that our models store `rating` as a Number which could possibly include floating point. I've never actually seen one but a lot of it is buried behind status bars. I seem to recall it's integer math but don't quote me just yet.

**Comment by DenverCoder1** [comment]
> would be nice to know if there the negative/positive equivalent/inverse of `nonNegativeInteger`

`nonNegativeInteger` is actually from shields.io's validator.js where effectively:

`nonNegativeInteger` is defined as `Joi.number().integer().min(0).required()`
`anyInteger` is defined as `Joi.number().integer().required()`
I suppose the same could be done for negative only by using max()

https://github.com/DenverCoderOne/shields/blob/5e6d68123a171c9d1deb73f01ea3d1396897e1ee/services/validators.js#L11-L14

**Comment by Martii** [comment]
There you go... confirmed it's positive/zero/negative integers *(i.e. integer math at this time)*.

**Comment by DenverCoder1** [comment]
Awesome, thanks :+1:

As per Caleb's comment (https://github.com/badges/shields/pull/8080#discussion_r897278144) about how Greasyfork's rating badges should be considered for a later time, I'm thinking this similarly could be made a separate PR from #8081 because it similarly is a different kind of rating system than the ones they usually support.

In the meantime, this should allow people to make it with custom dynamic badges, so that's great.

Thanks for all your help with this.

**Comment by Martii** [comment]
@DenverCoder1 

Thank you for all your help too... btw you'll probably be needing these for the normal coloring at some point:

https://github.com/OpenUserJS/OpenUserJS.org/blob/master/public/less/bootstrap/oujs-variables.less#L469-L483

... the `state-whatever-bg` is our normal coloring for backgrounds. Please ignore the comments as that is for a bootstrap migration *(and #1903 for some error foregrounds matching in the palette)* which is WAY down the road or if you want to show off some color samples I can apply them to dev and see how it looks all around and perhaps merge them in as a default system wide.

I am thinking...:
* when zero use `info` for `whatever` indicating a nominal
* when positive use `success` for `whatever` indicating a positive trend
* when negative use `warning` for `whatever` indicating a negative trend

If you feel it is doesn't have enough contrast and not readable text the current corresponding reference for the foreground is at:

https://github.com/OpenUserJS/OpenUserJS.org/blob/a9cbf7d6670d5232bae44f284129a63d758210fb/public/less/bootstrap/oujs-variables.less#L17-L19

I've temporarily unlocked this issue in case you want to add anything *(text or emoji)*. Please note it will relock within 24 hours of silence by our automation since it is closed. We're also displaying other solidarity colors atm but that will eventually revert to these code point references.

**Comment by Martii** [comment]
It's up to you but probably at least yellow/blue or informational/ and one of the greens for negative/zero/positive would be consistent with our Install button values currently used. 

I use warning on some items and `danger` on extreme cases... very rarely do I use green because our install button doesn't currently do that like USO - Count Issues did back in the USO days... just sort of a laid back approach and let the user decide based off a common pattern.

Btw I'm grateful you changed `downloads` to `installs` recently on that PR. :) I wasn't a deal breaker but it is our terminology to use Installs. :smile_cat:

**Comment by Martii** [comment]
@DenverCoder1 

As a "bad news" FYI...

Re: 

> if you could check their DoS protection e.g. do they really read headers and such as I'd rather not have our automation automatically ban them in case they are ignoring the well known headers.

We have found and confirmed strong, and repetitive, evidence in our logging that Shields is **not** reading and obeying the headers **at all** at the very least with dynamic badges. A DoS routine was implemented a few days ago as an additional test and it has been found that all three of Shields servers are promoting a potential DDoS attack vector by triggering and documenting the issue. While the ranges are not critical at this moment, due to the lack of interest by most Authors, it could be detrimental to **any site** since Shields isn't paying attention to them. We have had the complete dataset cross verified by another party.

The following time difference *(HMS)* is submitted for a snapshot snippet of 2020-07-08 for multiple requests to the same dataset object on a single server:

```
0:01:06         200
0:28:49         200
3:00:14         200
```

... as I mentioned over there we do have limits and they are clearly being ignored. It isn't even consistent from what we can tell. Multiplied by the current, known, three servers they utilize this is where their error becomes highly distributed.

Because this is a security issue we are unable to divulge additional specifics in public and are pursuing potential further action if needed.

This also explains a bit why NPM has been rate limiting Shields as well *(the mentioned 98%  (ish btw) instead of calebs implied 100%)*

> and we're very, very familiar with GitHub's rate limits and how to work with them at mass scale.

Apparently this isn't true across the board which is what our initial supposition was and is now confirmed that at "mass scale" this could be prove to be a huge issue.

**Comment by DenverCoder1** [comment]
I'm not sure there's much I can do about that.

They do have details about reporting security issues at https://github.com/badges/shields/blob/master/SECURITY.md including an email address.

I get that there was an argument earlier, but I find it would be more effective to try ending the argument rather than continuing it as it seems they're the only ones that can help with the issue. You can always thank people for their opinion even if you don't agree.
