### ISSUE TITLE
The Donate button does not work on this page

### ISSUE THREAD

**Issue by joeytwiddle** [OpenUserJS/OpenUserJS.org#1972]
**What happened?**

The Donate button is shown on this page, but when clicked, it does not work. (It just jumps to the top of the current page, due to the `#` URL.)

![195138428-0c7c3c5a-95f0-4e08-b3ec-16e988432b5b](https://user-images.githubusercontent.com/911799/195145044-f6da88f3-8e07-4e71-a08e-7f9227ef949f.png)

**What did you expect to happen?**

I expected clicking on the button would go directly to a donation website, such as Patreon, Liberapay, OpenCollective or PayPal.

**What the problem might be**

It looks like the JavaScript for that button has not been loaded.

**Possible solution**

You could put the link to the external website directly on the button, perhaps with `target="_blank"`, so it will work even if the JavaScript is not loaded.

**Why is this important**

Because the site's footer often appears below the fold, this might be the first time the user notices that button.

I don't know on which other pages this same issue may occur.

**Comment by Martii** [comment]
> The Donate button is shown on this page, but when clicked

It's working for me... however I don't get the same 400 page you have posted... because of that I will need to know your exact steps to reproduce i.e. exactly where you start and all clicks until you reach it including starting url.

Ref  *(Sorry about the poor capture quality... that's an issue to be remedied at some point)*:
* ![str 2022-10-12_11-48-38](https://user-images.githubusercontent.com/114709/195389883-b4913fbd-7292-4fb8-9621-248039362787.gif)

**Comment by joeytwiddle** [comment]
Cannot reproduce it today. It must have just been a temporary issue. Sorry!
