### ISSUE TITLE
Fetching raw source (with Unicode) is broken

### ISSUE THREAD

**Issue by trumpeta** [OpenUserJS/OpenUserJS.org#1990]
### What happened?

Hi, the raw source fetched using @require clause seems cut for some libraries.
I've checked the source code view at site's repository where the sources are still complete.
Not happening with all sources, just some.

### What did you expect to happen?

Raw source should match source code in HTML view.

### What the problem might be?

Site not sending whole source.

**Comment by Martii** [comment]
Thanks for making an issue here.

> Site not sending whole source.

Invalid assertion. As I mentioned on OUJS... this is a *terser* error. If you are unhappy with your over-exaggerated work-around *(try using just a single comment `//` which works for me on one of your libraries)* instead of the sensationalized:

>  appending about 100 to 200 comment chars

... which may be unnecessary.

If you find a minification error on this **experimental** feature of OUJS and no work-around please use the key from [here](https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/#unstableminify).

As further notice if the code shows up in the Source Code tab on OUJS then it's exactly what is served *(unminified of course)* via the direct .js and .user.js routes. i.e. they use the same exact routine to retrieve.

Only reason to keep this issue open is for potential migration from *terser*@*v*4.x to *terser*@*v*5.x migration... which is a known but not issued at this time.... albeit additionally tracked at #432 .

**Comment by Martii** [comment]
Okay so another user mentioned this and I guessed at the unminified target correctly.

I believe that I've found the Unicode issue. Please let me know if it's still doing it. If you do encounter it I expect a direct link to the source on OUJS so I can cross-check with it instead of guessing please so I don't have to close this as incomplete response.

**Comment by trumpeta** [comment]
The issue is gone, no significant chars are cut off on affected sources.
