### ISSUE TITLE
Support login using Keyoxide

### ISSUE THREAD

**Issue by sjehuda** [OpenUserJS/OpenUserJS.org#1995]
### What is missing?

Decentralized way to login.

Example: https://keyoxide.org/contact@forgejo.org

### Why?

Privacy

**Comment by Martii** [comment]
Couple of things:

1. A *passport* has to exist for an authentication method... See the lack of results at https://www.passportjs.org/search?q=Keyoxide and also with their JavaScript at https://www.passportjs.org/packages/ where it says "Start typing" for the current 538 strategies.
2. Since I'm unable to convince our glorious leader ;)  to add GitLab to the production auth strategies I seriously doubt I would be able to convince other strategies unfortunately. He does deserve that right though.

Because of item 1 I think it will never happen though... and that is a wontfix label at minimum.

Thanks for the suggestion though. :)

**Comment by sjehuda** [comment]
Thank you
