### ISSUE TITLE
Too many redirects 429 when logging in via GH or user search

### ISSUE THREAD

**Issue by pke** [OpenUserJS/OpenUserJS.org#2025]
### What happened?

https://openuserjs.org/users?q=pke gives 429
https://openuserjs.org/users?q=pk does not 

Also I am unable to login using my GH user name `pke`. Seems to be related and worked earlier today.
All cookies are cleared and different browsers used (Chrome, Firefox)

### What did you expect to happen?

Expect to be able to login via GH and search for user `pke`

### What the problem might be?

Since I am using different browser (which never logged into the site) the problem could be on GitHubs end.

**Comment by Martii** [comment]
All new users are "on probation" currently for one year and are only allowed to login once a day. i.e. don't log out until your session expires and wait a full day before hitting that page again... otherwise you get to start the period all over.

This is necessary for bad actors and we are rate limited everywhere that is important. This includes making too may calls to a route *(URL)* and queries are limited as well to prevent abuse.
