### ISSUE TITLE
Support connecting with XMPP

### ISSUE THREAD

**Issue by sjehuda** [OpenUserJS/OpenUserJS.org#2044]
### What is missing?

Connecting with XMPP.

XEP-0493: OAuth Client Login

> This specification details how a third-party can be securely granted access to an XMPP account without exposing the account credentials, using OAuth.

https://xmpp.org/extensions/xep-0493.html

### Why?

Because XMPP is autonomous and I can establish servers that are private and under my control.

**Comment by Martii** [comment]
Similar duplicate to #1995 ... not supported.

Ref(s):
* https://www.npmjs.com/search?q=passport-xmmp
* https://www.passportjs.org/search?q=xmmp

**Comment by Martii** [comment]
@sjehuda 

> Pardon for commenting here. 

Not pardoned. Warned! If you do that again that will be grounds for removal of the site... Discussion removed.

>  The comments are closed for ticket #2044.

Which means the issue is closed and not up for more discussion.

> Martii, would this be relevant if ther would be an NPM module that does that task (i.e. implement XEP-0493: OAuth Client Login)?

As discussed previously both criteria must be met. Passport and npm which is how development goes. There are no exceptions at this time.

The subject is complete so please do not attempt to use production as a development area again. You know better.
