### ISSUE TITLE
Allow username change

### ISSUE THREAD

**Issue by sizzlemctwizzle** [OpenUserJS/OpenUserJS.org#233]
Allow users to choose another unclaimed name.

Also, we should probably prevent users from registering with an email address as their username. A simple regex can catch this and we could display a message saying the their username will be display publicly.

**Comment by Martii** [comment]
@Lorentz83 

Your OUJS displayed username is now `Lorentz83`... this is a one time manual deal here.

**Comment by Lorentz83** [comment]
It works, thank you.

**Comment by JJanz** [comment]
Ok, so I went a similar way and registered using Google account but, instead of using my name (as, for example, GreasyFork does) it's using my email. =/
I tried to add my GitHub account hoping I could take Google away as authentication but can't remove (or change) them, just add. =/
Also, as yet seen in the topic, couldn't terminate the account and get in with GitHub as there's no Terminate Account. =/
Would you also keep my email private and change username, too, ASAP? (I'm not willing to write it here for the same reason I want to change it but OpenUserJs has it along with my GitHub username seen here.) Thanks in advance.

**Comment by Martii** [comment]
@JJanz

This won't be made easy for you as it's not easy for me... ;) :) *(slightly outlined at what I have to do too)*

> it's using my email.

Strange that you would refer to yourself as an "it" since **you appear to have skipped reading the huge caution box** I put in. ;).

So let me get this squared away here...
* You just created your [userscripts repo](/JJanz/userscripts) about an hour ago.
* You created your OUJS account without reading the caution box
* You want to disguise yourself by having an auth removed.
* Finally you do know that committing anything to GH requires authentication that anyone can view which is how I've found you in our DB... so this one time change in our DB is going to give you a false sense of security.

So what I can do... since I'm in a good mood... I can do the one time rename of your account to match here, however the auths you have chosen, especially your initial signup auth method, will be staying. You have to think before your do with OUJS instead of being a drone with other less evolved sites and processes.

/end giving you a hard time for not reading. ;) :)

P.S. Your username on OUJS is "JJanz" *(without the quotes of course)*

**Comment by Martii** [comment]
> (or change) them, just add

Btw something else for you to read... https://openuserjs.org/user/preferences in case you want to flip to GH as your primary. I would recommend this, especially around April 20th, 2015, since it's still a bit unclear on what is actually deprecated in googles oauth2.

**Comment by JJanz** [comment]
First, thanks a lot for being this fast. I really appreciate it.

Also, thanks so much for helping me out. It turned out to be exactly what I intented.

Then, I have to say: I DO NOT want to disguise myself by having an auth removed. It's not about disguising or security measures and there was no evidence to support your assumption (please don't be a detective ;) ). I thought the context made it perfectly clear but, since it might have not, I'll clarify: I was intending to get a less-spammy username through that. Once I have it, yes, I have no intention to remove it and it sure can stay. And, actually, one of those failed attempts for this more private username was flipping back/forth to/from GH as my primary.

And, as for the false sense of security, yes, I do know about it. I also do know my email addresses are exposed around the web by a few poorly constructed systems but it doesn't stop me from trying to avoid it as much as doable.

Last, **the huge caution box you put in**, which I DID read, is on top of 2 form fields visually glued together, which makes them appear connected. Being so, the Username field seems to mean my username in that service I'm choosing to register my account. There's no clue it's for me to choose a brand new username unrelated to the service. It's (unless I'm wrong) exactly what Lorentz83 went through, which is what I meant by "I went a similar way". And, also, NO OTHER service for which I used Google authentication got my email as username (GreasyFork was only mentioned as an example and suggestion, as they've got my name for that). So, considered all this as context, **the huge caution box you put in**, which I DID read, sounds like a warning for perhaps another of those authentication methods that might only give email for the system to rely on (and maybe use as username). And that, BTW, is what I meant by **it**: the system that seemed to have used my email as username (which, after all figured out, I realize I did mistakenly as it's actually from that field visually connected to the authentication service).

Hoping it's all cleared out, thanks again.

**Comment by Martii** [comment]
> the huge caution box you put in, which I DID read, is on top of 2 form fields visually glued together, which makes them appear connected.

So your connection wasn't made. ;) You should also realize that I've figured out when creation date has occurred which is why I knew it was a User mistake not a OUJS mistake. Making the leap of saying "some authentication methods may require email addies" isn't anywhere near the current message. Anyhow... thanks for the explanation of your intentions... if I feel a genuine request is asked I'll do my best to accommodate... in which you did but please realize this is nothing like Lorentz83 as that was prior to the notification. Anywho... you are welcome. :)

Bringing this to issue topic... there are several other factors, and other issues to be created and completed, that have to happen before this can even be considered so tagging as a later task. I still think the one time changing is better for accountability to prevent gaming of the system.

**Comment by JJanz** [comment]
> So your connection wasn't made. ;)

No it wasn't. ;)

> I've figured out when creation date has occurred which is why I knew it was a User mistake

Actually, no. I did created my GH userscripts repository after my OUJS account but my GH account is from 2012. I had no intention to connect the 2 until I noticed I could have a central place for scripts. However, my problem wasn't even GH related but a mistake I did make led by the semantics of 2 visually related form fields. So I'd like to suggest you guys to visually part them to help newcomers.

> the one time changing is better

Agreed. It would have helped me in the first place, undoing what I have confused and avoided you some not-quite-you-duty work.

> you are welcome. :)

Thank you. =)

**Comment by Martii** [comment]
> my problem wasn't even GH related

Wasn't suggesting that it was a GH issue.

> So I'd like to suggest you guys to visually part them to help newcomers.


As the notification states...
> "The unique Username that you choose to sign up with here will be displayed to everyone."

... is the first sentence... which you didn't connect with. I spent about a month deciding on the correct structure for the message so if you have a concise equal it will be considered... however it is painfully obvious that you missed reading it... perhaps lost in translation? So you may suggest but please include the suggestion rather than allude to it with "it could be parted"... that doesn't help anyone out. It is "glued", as you stated, for the exact reason... you typed in your email, you were cautioned, you did it anyways. :)

**Comment by JJanz** [comment]
> perhaps lost in translation?

Maybe. The text itself is fine and gave me the right message but what really troubled me into a second interpretation (which I took) was the context of the rest of the form, as I explained before. Which led me to my suggestion and hopefully ending the OT for this particular issue (sorry about that, you all).

> our system sanitized it to be non-email and compatible with the DB. :)

That was a good catch. =)

> please include the suggestion rather than allude to it with "it could be parted"... that doesn't help anyone out.

Sure. And, as I'm on it, I also suggest changing both "Username" placeholders in Login and Register fields to "OpenUserJS Username". It'd make clearer it's unrelated to the authentication service.

For the Register part, the select input for authentication service could be in a row below "**the huge caution box you put in**, which I DID read" (sorry, couldn't avoid getting that for its name =D ). And the select could also use a placeholder, maybe an option (disabled, selected by default and first) labeled "OAuth/OpenID service". Then the button could be in a row of its own, being a just 2 lines and a button for a registration form. But lines should not touch each other, keeping only "**the huge caution box you put in**, which I DID read" touching the input field it's related to, "OpenUserJS Username", making them semantically one field. So a good 5px+ or 10px as margin to the select and to the button would probably do for the visual separation.

**Comment by xlwmin** [comment]
Sorry, I made a mistake. I am Chinese, English is not good. When I registered,I didn't pay attention to the notice.So.., Can you help me modify my username to "xlwmin"?
Thanks in advance.

**Comment by Martii** [comment]
@xlwmin
> Can you help me modify my username to...

Complete. Omit the sanitized email portion when logging in e.g. what you wanted it changed to. Also both scripts had to be deleted including statistics as it's much easier and an intended consequence of migrating your account. However I reuploaded them in the order they were originally uploaded. 

Enjoy.

**Comment by xlwmin** [comment]
@Martii 
Thanks !

**Comment by sizzlemctwizzle** [comment]
I'm closing this since improvements have been made which so prevent this from being an issue. If you're registering, you'll have to type your desired username in first. Only then will be displayed sanitized in the registration form where you pick your authentication method. Kind of hard not to get the message that we want you to pick a username for your account on OUJS, not enter some type of login credential for your authentication provider.
