### ISSUE TITLE
Changing Script Name creates a new Script

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#266]
Changing the script name through "Edit Script" function creates a new script instead of just replacing the old one. Not sure if its a bug or a feature. 

Another issue is the script homepage url changes according to the script name. Both GreasyFork and MonkeyGuts are able to use a fixed url which makes bookmarks and implementing your own update scripts a lot easier.

**Comment by sizzlemctwizzle** [comment]
Just to clarify for the recent duplicate  (#1007), no user script engine supports a way to receive a script update with a name change (specifically @name + @namespace combo). Allowing this behavior on the site would lead a current user of the script with the original name to receive no further updates and they would have no way of knowing the new name of the script. You can still create a new script with the new name and delete the old script, but I'm discouraging this inconvenience to average users by forcing you to give up votes, install count, and issues just to make a minor vanity change. So I suggest script authors choose their script names wisely.

**Comment by derjanb** [comment]
> no user script engine supports a way to receive a script update with a name change

That's not entirely true. Tampermonkey wouldn't care. ;)

**Comment by Martii** [comment]
@sizzlemctwizzle 
Also the last thing we should allow is a security hole with spammers, hackers, and gamers *(as in install gaming)* that constantly change their script name in the same DB slot... which would usually install different scripts in most of the .user.js engines out there except the ones that **may not** follow the standard specifications from the master peer. *(e.g. Greasemonkey)*

> So I suggest script authors choose their script names wisely.

Yes some thought put into first is a good thing instead of just carelessly naming something and then allowing a .user.js engine to be irresponsible and:

> "...n't care"

**Comment by TimidScript** [comment]
The users do choose names wisely but the product is not constant and can change over the years. I mean some of these scripts change over their initial release and that is normal. Or because the site name changes, and that is essential. Even full blown software products do name changes, mostly for marketing reasons. 

If the author deals with the consequence automatic update, I see no issue with it. So no automatic update is a minor problem compared to the inability to change the name. 

> lso the last thing we should allow is a security hole with spammers

I really do not understand this issue. The update link will still point to the exact update location, and if the user wanted malicious software, he does not need to change the name. And I cannot limit anyone else outside OUJS to use the same header as one of my scripts (which has already been done in USO and OUJS).

But fair enough. Thanks for the reply.

**Comment by Martii** [comment]
> Even full blown software products do name changes, mostly for marketing reasons.

Pick XBMC to KODI... do you see KODI users installing XBMC to get KODI... **no you do not**. *(if you don't know what these are then do a search)*. When a name change comes along you install the new version... you don't automatically get stats from someone who hasn't been following you... they need to come along and do that themselves.

> So no automatic update is a minor problem compared to the inability to change the name.

The requirement, and **not** an inability of, of the original source naming is more paramount than the **whimsical need** to constantly change a script name. I've been in the industry for decades now and what you typed is "malarky" and misinformation for sure. Just because one site does it incorrectly doesn't mean everyone should.

A final comparison is the path to the script... if you look at OUJS and it's URI structure those would have to be changed as well... and would seriously mess up client installations. GM is centric on the UserScript metadata block with a fall back to the installation path... **NOT** the other way around. Unless sizzle overrides me *(which technically he already agrees and so do I with him)* I won't ever subscribe to pasting a number on a script. That was one of the most lamest features of USO and I'm glad to be rid of 37004 *(that was me btw)* and all the other ids I had... it's **not** an intelligent system, archaic, and should be buried where it belongs... in the past.

/admin soap box
