### ISSUE TITLE
Support registration with Mozilla Persona

### ISSUE THREAD

**Issue by Munto** [OpenUserJs/OpenUserJS.org#358]
I tried to register myself with Persona but I received the message "Unauthorized" with the following error:
"NetworkError: 401 Unauthorized - https://openuserjs.org/auth/"

**Comment by Martii** [comment]
External refs:
* https://mail.mozilla.org/pipermail/persona-notices/2016/000005.html  *(Mozilla to shut down persona)*
* http://www.ghacks.net/2016/01/12/mozilla-to-shut-down-persona-on-november-30-2016/

This is now a WONT FIX

**Comment by sizzlemctwizzle** [comment]
I guess I'm really glad I never got this working or else we would have had users locked out of their accounts. Sure we could forced them to authenticate with another provider when they logged in, but that would have been a real pain for everyone.

**Comment by yfdyh000** [comment]
"We intentionally designed Persona to expose email addresses rather than
opaque identifiers, which should ease the transition to other systems
that provide verified email addresses." in the mail.

**Comment by Martii** [comment]
@sizzlemctwizzle 

Yup... glad I never got it working too... the iframe they opened up would have caused all kinds of development issues too with the UI and how we authenticate... the demo worked but it crossed `iframe` boundries which could have been messy. I can say that we should limit Mozilla technologies since they have been dismantling just about everything.
