### ISSUE TITLE
Why are we not using bootstrap > 3.1.1?

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#379]
Just for grins I updated [bootstrap](https://github.com/twbs/bootstrap) dev locally to 3.2.0 and it appears in a quick scan to be okay to use e.g. my normal testings it appears to be okay... not fully tested though.

This question is primarily directed towards @Zren

**Comment by Martii** [comment]
@Zren 
I would appreciate you pointing me to the configuration file that you used for bootstrap 3.1.1 otherwise next week I will be reverse engineering it and generating one for OUJS. Thanks.

**Comment by Zren** [comment]
All manual changes to `/public/css/bootstrap-custom.css` need to be either moved to `common.css` or applied in the update.
https://github.com/OpenUserJs/OpenUserJS.org/commits/master/public/css/bootstrap-custom.css

As for the configuration:
https://github.com/OpenUserJs/OpenUserJS.org/issues/223
https://github.com/Zren/bootswatch-OpenUserJS.org/compare/84dd4c65daafecb0448f731f10617dce9aaf110d...theme

The changes to bootswatch are too many to list on github (mostly because there's 20 themes it's based off of.
https://github.com/thomaspark/bootswatch/compare/Zren:theme...thomaspark:gh-pages

Probably best to pull away from bootswatch as there's so much noise in the repo for the other themes. The stuff we'll punch into the [bootstrap customizer](http://getbootstrap.com/customize/) in all in the [variables.less](https://github.com/Zren/bootswatch-OpenUserJS.org/compare/84dd4c65daafecb0448f731f10617dce9aaf110d...theme#diff-862e5edd6f23fcccf2aece3ea17fbb4cR13) file. The extra junk is in the [bootswatch.less](https://github.com/Zren/bootswatch-OpenUserJS.org/compare/84dd4c65daafecb0448f731f10617dce9aaf110d...theme#diff-0220f385d868392d6bba303b9e57438eR2) file.

Did the variables stuff: https://gist.github.com/anonymous/03a4640ed537c1b0c92c
http://getbootstrap.com/customize/?id=03a4640ed537c1b0c92c

**Comment by Martii** [comment]
Reopening due to #541 

Will work on this next week a bit.

Thank you Zren for the linkage.

**Comment by Martii** [comment]
@Zren 

A few questions come to mind to help me understand bootstrap a little better

> All manual changes to...

Including your changes or just mine?

> Probably best to pull away from bootswatch...

Using the default theme of bootstrap itself there is no coloration for our current site colors. Is that included in [your gist](https://gist.github.com/anonymous/03a4640ed537c1b0c92c)? If so how exactly are we supposed to read in the JSON? *(Remember _grunt_ is currently way back on the burner and manual understanding is a must here... I've been twiddling with _less_ and "`myVars`" and there's some reference to JSON with [this link](http://stackoverflow.com/questions/19252248/load-variables-into-less-css-preprocessor-from-json-file))*

General question of why is there `bootstrap.css` and `bootstrap-theme.css` in the downloaded zip file from http://getbootstrap.com/customize/?id=03a4640ed537c1b0c92c ? *(This is also present in the dist folder of bootstrap... I understand the website whittles down what we don't use but when are we supposed to apply our own theme? `common.css` of course is loaded afterwards so I plan on moving Squada One there at some point)*

**Comment by Zren** [comment]
> Including your changes or just mine?

Yours. All of mine are from modifying the .less files and not the .css file itself.

> General question of why is there `bootstrap.css` and bootstrap-theme.css

Because you need to include both `bootstrap.css` and `bootstrap-theme.css`. Bootswatch combined the two files into a single file. The first is the default bootstrap file, the second is a file that overrides all the previous rules with the different variable values. You'll also need to put https://github.com/Zren/bootswatch-OpenUserJS.org/blob/theme/custom/bootswatch.less into a 3rd file or dump it into the top of common.css.
