### ISSUE TITLE
Link to license-page?

### ISSUE THREAD

**Issue by ardiman** [OpenUserJS/OpenUserJS.org#438]
Hi,
it would be nice if meta code for license like:

``` javascript
// @license      CC BY-NC-SA 3.0; https://creativecommons.org/licenses/by-nc-sa/3.0/
```

showed a _real_ link to the given url (here: https://creativecommons.org/licenses/by-nc-sa/3.0/) on the script page .

A link like
[CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/)
would be even better.

Thank you.

**Comment by Martii** [comment]
@ardiman 

This should be complete. Please note that all of your scripts utilizing CC only *(which is a Content License)* need to declare an OSI Code License SPDX short identifier when you utilize the `@license` key. e.g `CC BY-NC-SA 3.0` isn't valid any more. Please use `CC-BY-NC-SA-3.0` and the optional web url following it with a `; `. In long format `@license CC-BY-NC-SA-3.0; https://creativecommons.org/licenses/by-nc-sa/3.0/legalcode`. 

`MIT` is the least restrictive/permissive of all the Code Licenses so I recommend **at minimum** you do this from the information passed on by legal counsel:

``` js
@license CC-BY-NC-SA-3.0
@license MIT
```

`MIT` must be last in the metadata block to conform to the Terms of Service... but you can still do dual-licensing provided the SPDX short id exists.

After some time **we're going to require the OSI `@license` key so arbitration won't be necessary with new and updated scripts. Much easier on administration. :)

Thanks,

Closing... if there are any specific issues to this issue please notate here with a mention to myself... otherwise open a new issue with a more specific request.


Further reading:
* https://openuserjs.org/announcements/Licensing_enforcement
* https://openuserjs.org/user/add/scripts ... filled out `@license` a bit.
