### ISSUE TITLE
Implement favourite system

### ISSUE THREAD

**Issue by jerone** [OpenUserJs/OpenUserJS.org#461]
Right now on script pages there's a favourite button that is disabled and appears to have [no logic](https://github.com/OpenUserJs/OpenUserJS.org/blob/master/views/includes/scriptUserToolsPanel.html#L15).

It would be nice if users could favourite userscripts.

Also, [favorite vs. favourite](http://grammarist.com/spelling/favorite-favourite/)?

Side discussion; should favoring be part of the scripts rating math... 

Ref: https://openuserjs.org/discuss/Favorite_Button_working

**Comment by sizzlemctwizzle** [comment]
I'd rather just implement a page that shows what scripts you have upvoted, and get rid of that favorite button. It seems redundant to me.

**Comment by Martii** [comment]
@sizzlemctwizzle 
As long as there isn't any other related issue to it's current isolation e.g. notifications interaction for example on favorite items versus notifications on upvoting items then I won't see an issue with removal. GH's "watch" nomenclature is more accurate than a favorite system so that is how I am taking this issue in my own modified context.

**Comment by sizzlemctwizzle** [comment]
I'm to close this issue in favor of listing scripts a user has upvoted.
