### ISSUE TITLE
Syncing from Github does not work

### ISSUE THREAD

**Issue by devnoname120** [OpenUserJs/OpenUserJS.org#599]
I have set a WebHook on my [Github repository](https://github.com/HandyUserscripts/AntiAdware) so that my script [AntiAdware](https://openuserjs.org/scripts/devnoname120/AntiAdware) automatically gets synchronized.

Although the server answers with a response code 200 to the deliveries made by Github, my script is not updated on OpenUserJS.

Can you please check this?

**Comment by Martii** [comment]
Sync's okay for me at Wed Mar 11 2015 20:27:48 GMT+0000 (UTC) with [OUJS script](https://openuserjs.org/scripts/Marti/RFC_2606%C2%A73_-_Hello,_World!) and [GH repo commit](/Martii/UserScripts/commit/973a624596954ed6e231e7d2877ad937e38ab9f2).

Regarding [a comment on OUJS](https://openuserjs.org/scripts/devnoname120/AntiAdware/issues/Update#comment-14c0a6bf84e) of:
> I have set OpenUserJS to automatically synchronize with my Github repository, but it does not seem to work.

That's because your username on OUJS and GH is @devnoname120 and not @HandyUserscripts... your account on GH has to own [the source script](https://github.com/HandyUserscripts/AntiAdware) being sync'd to your account on OUJS... in which you don't appear to be. Let me know if you need anything else.
