### ISSUE TITLE
Still having problems with my email showing up as my username

### ISSUE THREAD

**Issue by moshmage** [OpenUserJs/OpenUserJS.org#652]
Is there no fix for this yet? :(

**Comment by Martii** [comment]
That's because you haven't been following along. :)

I will attempt to get to this the next few days... in the meantime please don't post anything on OUJS as I get to do this manually at the moment and if a lot shows up all of the sudden I'll just file 13 the account and we'll start over. I will slap a comment in here when it is done.

See also:
* #251 
* #359

**Comment by moshmage** [comment]
You da man!

**Comment by Martii** [comment]
**You are changed**.... however there is one slight quirk that I can't fix... your script sources are linked with your original username... therefor they aren't accessible under your new name of *moshmage*... what you need to do is reupload all of them... your metadata should stay intact for this e.g. install counts... you still have ownership to your comments and script homepages... but the script source under the old username is orphaned... please reupload your sources... do one and if everything goes well then do the rest.

**Comment by Martii** [comment]
@moshmage 
Please don't leave those affected scripts un-reuploaded... I'll be deleting them later this evening if they aren't reuploaded.

**Comment by Martii** [comment]
Removed 4 orphaned script homepages... all the OUJS metadata for these scripts are lost... you are welcome to re-upload them at a later date but you get to start over with the stats. Closing.

**Comment by moshmage** [comment]
@Martii No problemo on the orphaned scripts, I'll re-upload 'em again when I have the time; Also, don't mind the status of those :)
