### ISSUE TITLE
Script Group counter

### ISSUE THREAD

**Issue by Dexmaster** [OpenUserJS/OpenUserJS.org#93]
Group counter doesn't decrement after script was deleted.

**Comment by Martii** [comment]
Just a FYI here for this one... the code at https://github.com/OpenUserJS/OpenUserJS.org/blob/69e99bcf143e63701750a9dc46679db2e5c7ccf2/libs/modelParser.js#L567-L569 is showing it to self correct the size when I made it every 10 seconds, deleted a script added to an existing group, and refreshed the page at about 15 seconds later. e.g. wait 2 hours currently and I think it indeed does correct itself on the "Size" column for this use case.

Although I have been noticing `Script._id`'s that are no longer around in `Group._scriptIds` which may affect the rating or something else perhaps. Looking into it.

**Comment by Martii** [comment]
And if it's the only script in the group that's when it doesn't reset after the modified 10 second period.

**Comment by Martii** [comment]
ffa194b012b540353c7871c8fedfc9c0ef6fbc51

**Comment by Martii** [comment]
> I totally forgot about that use case.

So here's a use case scenario...

Add new script to group then delete; add new script to group, then delete; add new script to group, then delete; add new script to group, then delete; add new script to group, then delete; etc.

... causing lots of Script queries. While this can be indexed it's still consuming resources. Yes there has been precedence for this which is why the commit references are in this issue to curtail some of that.

I think the two hour interval between resynching is the right way to go and is currently a post op on access *(PPP, restful)*... albeit that max value might be able to be tweaked a little. We'll see how this goes over the next long term period and see if it needs adjustment. :)

**Comment by Martii** [comment]
Closing from no further comments. Please leave a message if the issue resurges outside of that period.
