### ISSUE TITLE
More web browsers that support UserJs

### ISSUE THREAD

**Issue by GreenLunar** [OpenUserJS/OpenUserJS.org#938]
https://openuserjs.org/about/dwb (built-in)
http://portix.bitbucket.org/dwb/

https://openuserjs.org/about/Jumanji (built-in)
https://pwmt.org/projects/jumanji/

https://openuserjs.org/about/Midori (plugin)
http://midori-browser.org/

https://openuserjs.org/about/Otter (built-in) https://github.com/OtterBrowser/otter-browser/issues/336
http://otter-browser.org/

~~https://openuserjs.org/about/Uzbl (n/a)~~
~~http://uzbl.org/~~

I have not used Uzbl. Support for UserJs is either built-in or available by using [userscript.sh](http://github.com/singpolyma/singpolyma/blob/master/uzbl/data/scripts/userscript.sh). See [script](http://www.uzbl.org/wiki/scripts#scripts_that_alter_webpage).

**Comment by Martii** [comment]
Needs some screenshots... I haven't been able to do QupZilla yet esp. since I can't build it with current distro Qt. e.g. look at the existing .user.js engines and model after that. If it's native then we don't have a doc template for that just yet... still pondering exactly how to do this without going overboard. Please read [the dev wiki](https://github.com/OpenUserJs/OpenUserJS.org/wiki) for image usage.

Docs I don't mind if we're in [a **blocking** state](https://github.com/OpenUserJs/OpenUserJS.org/issues?q=is%3Aissue+is%3Aopen+label%3ABLOCKING), which we are, but I have little time to validate every browser out there... perhaps a webkit page with these in the short term might be an option.

If you wish to assign yourself to do this task please do so... however it requires one other to merge as per the CONTRIBUTING.md... Active Maintainer, that's me, can push something through if it's critical.

Notes: 
* Not having all the intel is something that I could veto... 
* Not real thrilled about a beginners guide on how to exec bash shell scripts... that might be beyond the HOWTO.

**Comment by GreenLunar** [comment]
CC @Emdek and @OtterBrowser

See also #909 https://openuserjs.org/about/QupZilla

Once you have a sensible UI for UserJs script, please do send a PR to add OttoBrowser to OpenUserJS.org

**Comment by GreenLunar** [comment]
Perhaps dwb, Jumanji and Uzbl would be referenced in a single page, just so people would know they have support for UserJs scripts.  I think, Midori has a sensible UI for end-users, and Otter would probably have one too.

**Comment by Martii** [comment]
So retested the remaining.... Midori and Otter may someday have some promise in the future however development is too dated and some things work and others don't.

I've updated the current list at https://github.com/OpenUserJS/OpenUserJS.org/issues/938#issuecomment-201195166

Closing this list of browsers as they are all currently veto'd by myself as Active Maintainer. Should Otter and Midori get a stabler release please open another issue per browser.
